version: '2.1'

services:
  eureka-sv:
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'sale-network'
  carrito:
    build: carrito
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - 'sale-network'
  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "443:443"
    networks:
      - 'sale-network'
  productos:
    build: productos
    mem_limit: 512m
    ports:
      - "8081:8081"
    networks:
      - 'sale-network'
  ventas:
    build: ventas
    mem_limit: 512m
    ports:
      - "8083:8083"
    networks:
      - 'sale-network'
networks:
  sale-network: